# -*- coding: utf-8 -*-
"""Auditoría ELT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywISGw78xL1vZ27NLoSCy8rL3l-eYfAQ
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()
csv_file = list(uploaded.keys())[0]

df = pd.read_csv(csv_file)
df.head()

# =====================================
# AUDITAR CARGA DE PERSONAS + EMPRESAS
# =====================================

from google.colab import auth
import pandas as pd
import gspread
from google.auth import default
from googleapiclient.discovery import build
from openpyxl.utils import get_column_letter
import urllib.parse

# =====================================
# 1. AUTH
# =====================================
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
service = build("sheets", "v4", credentials=creds)
drive_service = build("drive", "v3", credentials=creds)

# =====================================
# 2. PREPARAR DATAFRAME
# =====================================
df["Added On Date"] = pd.to_datetime(
    df["Added On"],
    format="%m/%d/%Y %I:%M %p",
    errors="coerce"
).dt.strftime("%d/%m/%Y")

df = df.replace([float("inf"), float("-inf")], "")
df = df.fillna("")
df = df.astype(str)

# =====================================
# 3. CREAR GOOGLE SHEET (NOMBRE ÚNICO)
# =====================================
base_name = input("Nombre del Google Sheet / Cliente: ")
final_name = base_name
i = 1

while True:
    r = drive_service.files().list(
        q=f"name='{final_name}' and mimeType='application/vnd.google-apps.spreadsheet' and trashed=false",
        fields="files(id)"
    ).execute()
    if not r["files"]:
        break
    final_name = f"{base_name} ({i})"
    i += 1

spreadsheet = gc.create(final_name)
sheet = spreadsheet.sheet1
sheet.update_title("Base")
sheet.update([df.columns.tolist()] + df.values.tolist())

SPREADSHEET_ID = spreadsheet.id
BASE_SHEET_ID = sheet._properties["sheetId"]
last_row = len(df) + 1

# =====================================
# 4. ÍNDICES
# =====================================
EMAIL_COL_INDEX = df.columns.get_loc("Email")
EMAIL_LETTER = get_column_letter(EMAIL_COL_INDEX + 1)

DATE_REAL_INDEX = 19
WEEK_INDEX = 20
MONTH_INDEX = 21
QUARTER_INDEX = 22
DOMAIN_INDEX = 23  # NUEVA COLUMNA

# =====================================
# 5. EXPANDIR GRID
# =====================================
service.spreadsheets().batchUpdate(
    spreadsheetId=SPREADSHEET_ID,
    body={
        "requests": [{
            "updateSheetProperties": {
                "properties": {
                    "sheetId": BASE_SHEET_ID,
                    "gridProperties": {
                        "columnCount": DOMAIN_INDEX + 1
                    }
                },
                "fields": "gridProperties.columnCount"
            }
        }]
    }
).execute()

# =====================================
# 6. COLUMNAS DERIVADAS (T–X)
# =====================================
requests = [

    # Fecha real
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":DATE_REAL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Added On Date (Date)"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":DATE_REAL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":'=IF(S2="","",DATE(RIGHT(S2,4),MID(S2,4,2),LEFT(S2,2)))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Semana
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":WEEK_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Semana del año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":WEEK_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":'=IF(T2="","",TEXT(WEEKNUM(T2,21),"00")&" - "&TEXT(T2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Mes
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":MONTH_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Mes - Año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":MONTH_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":'=IF(T2="","",TEXT(T2,"MM")&" - "&TEXT(T2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Quarter
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":QUARTER_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Quarter - Año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":QUARTER_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":'=IF(T2="","","Q"&ROUNDUP(MONTH(T2)/3,0)&" - "&TEXT(T2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # EMAIL DOMAIN (NUEVO)
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":DOMAIN_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Email Domain"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":DOMAIN_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({EMAIL_LETTER}2="","",LOWER(TRIM(MID({EMAIL_LETTER}2,FIND("@",{EMAIL_LETTER}2)+1,100))))'
            }}]}],
        "fields":"userEnteredValue"}}
]

service.spreadsheets().batchUpdate(
    spreadsheetId=SPREADSHEET_ID,
    body={"requests": requests}
).execute()

# Copiar fórmulas hacia abajo
for col in [DATE_REAL_INDEX, WEEK_INDEX, MONTH_INDEX, QUARTER_INDEX, DOMAIN_INDEX]:
    service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{
            "copyPaste":{
                "source":{"sheetId":BASE_SHEET_ID,"startRowIndex":1,"endRowIndex":2,
                          "startColumnIndex":col,"endColumnIndex":col+1},
                "destination":{"sheetId":BASE_SHEET_ID,"startRowIndex":1,"endRowIndex":last_row,
                               "startColumnIndex":col,"endColumnIndex":col+1},
                "pasteType":"PASTE_FORMULA"}}]}
    ).execute()

# =====================================
# 7. FUNCIÓN PIVOT (GENÉRICA)
# =====================================
def crear_pivot(nombre, fila_index, value_index):

    res = service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{"addSheet":{"properties":{"title":nombre}}}]}
    ).execute()

    pid = res["replies"][0]["addSheet"]["properties"]["sheetId"]

    pivot = {
        "pivotTable":{
            "source":{
                "sheetId":BASE_SHEET_ID,
                "startRowIndex":0,
                "startColumnIndex":0,
                "endRowIndex":last_row,
                "endColumnIndex":DOMAIN_INDEX+1},
            "rows":[{
                "sourceColumnOffset":fila_index,
                "showTotals":True,
                "sortOrder":"ASCENDING"}],
            "values":[{
                "sourceColumnOffset":value_index,
                "summarizeFunction":"COUNTA"}]
        }
    }

    service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{
            "updateCells":{
                "start":{"sheetId":pid,"rowIndex":0,"columnIndex":0},
                "rows":[{"values":[pivot]}],
                "fields":"pivotTable"}}]}
    ).execute()

# =====================================
# 8. CREAR PIVOTS
# =====================================

# PERSONAS
crear_pivot("Pivot Carga Diaria", DATE_REAL_INDEX, EMAIL_COL_INDEX)
crear_pivot("Pivot Semanal", WEEK_INDEX, EMAIL_COL_INDEX)
crear_pivot("Pivot Mensual", MONTH_INDEX, EMAIL_COL_INDEX)
crear_pivot("Pivot Quarterly", QUARTER_INDEX, EMAIL_COL_INDEX)

# EMPRESAS
crear_pivot("Empresas Diario", DATE_REAL_INDEX, DOMAIN_INDEX)
crear_pivot("Empresas Semanal", WEEK_INDEX, DOMAIN_INDEX)
crear_pivot("Empresas Mensual", MONTH_INDEX, DOMAIN_INDEX)
crear_pivot("Empresas Quarterly", QUARTER_INDEX, DOMAIN_INDEX)

# =====================================
# 9. LINKS METABASE
# =====================================
cliente = urllib.parse.quote(final_name)
base_url = "https://metabase.wearesiete.com/question/102-carga-de-personas-totales-a-reply"

print("\n📊 DASHBOARDS METABASE")
print(f"Día:     {base_url}?granularity=Day&cliente={final_name}")
print(f"Semanal: {base_url}?granularity=Week&cliente={final_name}")
print(f"Mensual: {base_url}?granularity=Month&cliente={final_name}")
print(f"Quarter: {base_url}?granularity=Quarter&cliente={final_name}")

print("\n📄 GOOGLE SHEET")
print(spreadsheet.url)

print("\n📄 REUS PROSPECCIÓN")
print("https://reusprospection.wearesiete.com/")

# =====================================
# AUDITAR ENVÍO DE CORREOS (PERSONAS + EMPRESAS + REPLY RATES)
# =====================================

from google.colab import auth
import pandas as pd
import gspread
from google.auth import default
from googleapiclient.discovery import build
from openpyxl.utils import get_column_letter

# =====================================
# 1. AUTH
# =====================================
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
service = build("sheets", "v4", credentials=creds)

# =====================================
# 2. PREPARAR DATAFRAME
# =====================================
parsed_dates = pd.to_datetime(
    df["Delivery date"],
    format="%a, %d %b %Y %H:%M:%S",
    errors="coerce"
)

df["Delivery Date Text"] = parsed_dates.where(
    df["Contacted"].astype(str) == "1"
).dt.strftime("%d/%m/%Y")

df = df.replace([float("inf"), float("-inf")], "")
df = df.fillna("")
df = df.astype(str)

# =====================================
# 3. CREAR GOOGLE SHEET
# =====================================
spreadsheet = gc.create("Auditoria Correos")
sheet = spreadsheet.sheet1
sheet.update_title("Base")
sheet.update([df.columns.tolist()] + df.values.tolist())

SPREADSHEET_ID = spreadsheet.id
BASE_SHEET_ID = sheet._properties["sheetId"]
last_row = len(df) + 1

# =====================================
# 4. ÍNDICES
# =====================================
TEXT_COL_INDEX = df.columns.get_loc("Delivery Date Text")
DATE_COL_INDEX = TEXT_COL_INDEX + 1
WEEK_COL_INDEX = DATE_COL_INDEX + 1
MONTH_COL_INDEX = DATE_COL_INDEX + 2
QUARTER_COL_INDEX = DATE_COL_INDEX + 3
EMAIL_COL_INDEX = df.columns.get_loc("Contact email")
DOMAIN_COL_INDEX = QUARTER_COL_INDEX + 1

col_letter = get_column_letter(TEXT_COL_INDEX + 1)
date_letter = get_column_letter(DATE_COL_INDEX + 1)
email_letter = get_column_letter(EMAIL_COL_INDEX + 1)

# =====================================
# 5. EXPANDIR GRID
# =====================================
service.spreadsheets().batchUpdate(
    spreadsheetId=SPREADSHEET_ID,
    body={
        "requests": [{
            "updateSheetProperties": {
                "properties": {
                    "sheetId": BASE_SHEET_ID,
                    "gridProperties": {
                        "columnCount": DOMAIN_COL_INDEX + 1
                    }
                },
                "fields": "gridProperties.columnCount"
            }
        }]
    }
).execute()

# =====================================
# 6. COLUMNAS DERIVADAS
# =====================================
requests = [

    # Fecha real
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":DATE_COL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Delivery Date (Date)"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":DATE_COL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({col_letter}2="","",DATE(RIGHT({col_letter}2,4),MID({col_letter}2,4,2),LEFT({col_letter}2,2)))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Semana
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":WEEK_COL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Semana del año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":WEEK_COL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({date_letter}2="","",TEXT(WEEKNUM({date_letter}2,21),"00")&" - "&TEXT({date_letter}2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Mes
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":MONTH_COL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Mes - Año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":MONTH_COL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({date_letter}2="","",TEXT({date_letter}2,"MM")&" - "&TEXT({date_letter}2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Quarter
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":QUARTER_COL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Quarter - Año"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":QUARTER_COL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({date_letter}2="","","Q"&ROUNDUP(MONTH({date_letter}2)/3,0)&" - "&TEXT({date_letter}2,"YY"))'
            }}]}],
        "fields":"userEnteredValue"}},

    # Email Domain
    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":0,"columnIndex":DOMAIN_COL_INDEX},
        "rows":[{"values":[{"userEnteredValue":{"stringValue":"Email Domain"}}]}],
        "fields":"userEnteredValue"}},

    {"updateCells":{
        "start":{"sheetId":BASE_SHEET_ID,"rowIndex":1,"columnIndex":DOMAIN_COL_INDEX},
        "rows":[{"values":[{
            "userEnteredValue":{
                "formulaValue":
                f'=IF({email_letter}2="","",LOWER(TRIM(MID({email_letter}2,FIND("@",{email_letter}2)+1,100))))'
            }}]}],
        "fields":"userEnteredValue"}}
]

service.spreadsheets().batchUpdate(
    spreadsheetId=SPREADSHEET_ID,
    body={"requests": requests}
).execute()

# Copiar fórmulas hacia abajo
for col in [DATE_COL_INDEX, WEEK_COL_INDEX, MONTH_COL_INDEX, QUARTER_COL_INDEX, DOMAIN_COL_INDEX]:
    service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{
            "copyPaste":{
                "source":{"sheetId":BASE_SHEET_ID,"startRowIndex":1,"endRowIndex":2,
                          "startColumnIndex":col,"endColumnIndex":col+1},
                "destination":{"sheetId":BASE_SHEET_ID,"startRowIndex":1,"endRowIndex":last_row,
                               "startColumnIndex":col,"endColumnIndex":col+1},
                "pasteType":"PASTE_FORMULA"}}]}
    ).execute()

# =====================================
# 7. PIVOTS PERSONAS Y EMPRESAS
# =====================================

def crear_pivot(nombre, fila_index, value_index):

    res = service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{"addSheet":{"properties":{"title":nombre}}}]}
    ).execute()

    pid = res["replies"][0]["addSheet"]["properties"]["sheetId"]

    pivot = {
        "pivotTable":{
            "source":{
                "sheetId":BASE_SHEET_ID,
                "startRowIndex":0,
                "startColumnIndex":0,
                "endRowIndex":last_row,
                "endColumnIndex":DOMAIN_COL_INDEX+1},
            "rows":[{
                "sourceColumnOffset":fila_index,
                "showTotals":True,
                "sortOrder":"ASCENDING"}],
            "values":[{
                "sourceColumnOffset":value_index,
                "summarizeFunction":"COUNTA"}]
        }
    }

    service.spreadsheets().batchUpdate(
        spreadsheetId=SPREADSHEET_ID,
        body={"requests":[{
            "updateCells":{
                "start":{"sheetId":pid,"rowIndex":0,"columnIndex":0},
                "rows":[{"values":[pivot]}],
                "fields":"pivotTable"}}]}
    ).execute()


crear_pivot("Personas Diario", DATE_COL_INDEX, EMAIL_COL_INDEX)
crear_pivot("Personas Semanal", WEEK_COL_INDEX, EMAIL_COL_INDEX)
crear_pivot("Personas Mensual", MONTH_COL_INDEX, EMAIL_COL_INDEX)
crear_pivot("Personas Quarterly", QUARTER_COL_INDEX, EMAIL_COL_INDEX)

crear_pivot("Empresas Diario", DATE_COL_INDEX, DOMAIN_COL_INDEX)
crear_pivot("Empresas Semanal", WEEK_COL_INDEX, DOMAIN_COL_INDEX)
crear_pivot("Empresas Mensual", MONTH_COL_INDEX, DOMAIN_COL_INDEX)
crear_pivot("Empresas Quarterly", QUARTER_COL_INDEX, DOMAIN_COL_INDEX)

# =====================================
# 8. REPLY RATES (LÓGICA SQL EXACTA)
# =====================================
df_original = df.copy()

df_reply = df_original.copy()

df_reply["delivery_date"] = pd.to_datetime(
    df_original["Delivery date"],
    format="%a, %d %b %Y %H:%M:%S",
    errors="coerce"
).dt.date


df_reply["Replied"] = pd.to_numeric(df_reply["Replied"], errors="coerce")
df_reply["Delivered"] = pd.to_numeric(df_reply["Delivered"], errors="coerce")
df_reply["Contacted"] = pd.to_numeric(df_reply["Contacted"], errors="coerce")

df_reply["valid_base"] = (
    (df_reply["Delivered"] == 1) &
    (df_reply["Contacted"] == 1)
)

df_reply["valid_reply"] = (
    (df_reply["Replied"] == 1) &
    (df_reply["Contacted"] == 1)
)

df_reply["day"] = df_reply["delivery_date"].astype(str)

df_reply["week"] = df_reply["delivery_date"].apply(
    lambda x: f"{x.strftime('%V')} - {x.strftime('%y')}" if pd.notnull(x) else None
)

df_reply["month"] = df_reply["delivery_date"].apply(
    lambda x: f"{x.strftime('%m')} - {x.strftime('%y')}" if pd.notnull(x) else None
)

df_reply["quarter"] = df_reply["delivery_date"].apply(
    lambda x: f"Q{((x.month-1)//3)+1} - {x.strftime('%y')}" if pd.notnull(x) else None
)


def calcular_reply_rate(df, periodo_col):

    resultados = []

    for periodo, grupo in df.groupby(periodo_col):

        base = grupo.loc[grupo["valid_base"], "Contact email"].nunique()
        replies = grupo.loc[grupo["valid_reply"], "Contact email"].nunique()

        reply_rate = round(replies / base, 4) if base > 0 else 0

        # 🔥 Convertir fechas a string si es tipo date
        if isinstance(periodo, (pd.Timestamp, )):
            periodo = periodo.strftime("%Y-%m-%d")
        elif hasattr(periodo, "strftime"):
            periodo = periodo.strftime("%Y-%m-%d")

        resultados.append({
            "Period": str(periodo),
            "Base": int(base),
            "Replies": int(replies),
            "Reply Rate": reply_rate
        })

    return pd.DataFrame(resultados).sort_values("Period")


    # 🔥 limpieza anti-NaN para JSON
    resultado_df = resultado_df.replace([float("inf"), float("-inf")], None)
    resultado_df = resultado_df.where(pd.notnull(resultado_df), None)

    return resultado_df

reply_day = calcular_reply_rate(df_reply, "day")
reply_week = calcular_reply_rate(df_reply, "week")
reply_month = calcular_reply_rate(df_reply, "month")
reply_quarter = calcular_reply_rate(df_reply, "quarter")

def subir_reply_sheet(nombre, dataframe):

    new_sheet = spreadsheet.add_worksheet(
        title=nombre,
        rows=str(len(dataframe)+10),
        cols="5"
    )

    new_sheet.update(
        [dataframe.columns.tolist()] + dataframe.values.tolist()
    )

subir_reply_sheet("Reply Rate Diario", reply_day)
subir_reply_sheet("Reply Rate Semanal", reply_week)
subir_reply_sheet("Reply Rate Mensual", reply_month)
subir_reply_sheet("Reply Rate Quarterly", reply_quarter)

print("\n📄 GOOGLE SHEET")
print(spreadsheet.url)
print("\n✅ Personas + Empresas + Reply Rates generados correctamente")